### ISSUE TITLE
Plugin does not add back log subscriptions if manually deleted

### ISSUE THREAD

**Issue by paulalex** [dougmoscrop/serverless-plugin-log-subscription#23]
I added the log subscriptions with the global setting and wanted to turn it off but I noticed once created this had no effect so I manually deleted the log subscriptions and then re-ran my pipeline and they never get created again.

**Comment by dougmoscrop** [comment]
This is generally not how any plugins within the serverless ecosystem work, save for a few that are doing API calls instead of CloudFormation - this is how CloudFormation wroks. You have created 'drift' in your stack.  You should be able to disable/remove this plugin, do a deploy, and then add it back and trigger recreation.  I don't know if CloudFormation Drift Detection has some magic that can help you but how I ^ mentioned it is what I would do if I was in your position.

**Comment by paulalex** [comment]
Ok thanks for the reply, I use terraform and do not really use cloudformation. I assumed it would work in the same way as terraform and if changes were made on the console it would detect this through some state and correct it.

**Comment by dougmoscrop** [comment]
Yeah that is the biggest stumbling point - everybody thinks CloudFormation is higher level than it really is!
