### ISSUE TITLE
Please add DependsOn support for adding lambda permissions

### ISSUE THREAD

**Issue by et304383** [dougmoscrop/serverless-plugin-log-subscription#30]
If the function to which one is adding the lambda permissions doesn't exist yet, CloudFormation throws an error when creating the LambdaPermission resource.

There are reasons I don't want to put GetAtt into the destinationArn field, so it would be nice to have the ability to enforce the function is created first via DependsOn.

**Comment by dougmoscrop** [comment]
Can you tell me more about why you don't want to use GetAtt?

**Comment by et304383** [comment]
> Can you tell me more about why you don't want to use GetAtt?

Not sure it's relevant. Just hoping we can have this feature at some point.

**Comment by dougmoscrop** [comment]
Well, the feature doesn't make sense to me, so I was trying to understand what you were trying to accomplish, and you are demonstrating a lighter version of the [XY Problem](https://en.wikipedia.org/wiki/XY_problem)

This plugin takes a `destinationArn` because that's what the `CloudWatch::Logs::Subscription` needs.   But Lambda Permissions take a function name.  I don't understand how the PR https://github.com/dougmoscrop/serverless-plugin-log-subscription/pull/7 that added permissions can even work, I shouldn't have merged it.  It's passing a destinationArn in to a property that says FunctionName. At least with GetAtt, I could have tried to look at GetAtt[0] and seen if it is the logical ID of a resource, and if that resource is a lambda, then I could have used Ref to get the Lambda name automatically.

Anyway, if you can figure out how you want this to work, a PR is welcome.

**Comment by dougmoscrop** [comment]
Ah, it would make sense that it worked because you can usually specify a Lambda Function Name or ARN, but I still don't understand how that would get translated in to a CloudFormation Resource ID for use in DependsOn.
