### ISSUE TITLE
FeatureRequest: DisableLogs option is not taken into account

### ISSUE THREAD

**Issue by traoreak** [dougmoscrop/serverless-plugin-log-subscription#67]
Hello, I am using your plugin in the latest version and I assumed that the plugin would take the "disableLogs" option that is supported by the serverless framework as mentioned on this page https://www.serverless.com/framework/docs/providers/aws/guide/functions. What I am requesting is for the plugin to ignore both the function where "logSubscription: false" is added and also where "disableLogs" is added since that's the default behavior with the framework. Do you think that's feasible ? If so I would gladly make a pull request for that. Thanks in advance

**Comment by dougmoscrop** [comment]
Thanks for bringing this up - I think the only confusing point would be that I don't know if disableLogs actually disables them entirely? If you don't create the LogGroup via CloudFormation, Lambda will still try to create it when the function is invoked, and some users might have disableLogs set up this way (with a function that still has the IAM execution role allowing it to create the log groups) simply because they don't want the log groups to be deleted, or they are pre-existing, but would still benefit from being able to subscribe to them. Does that make any sense?

**Comment by traoreak** [comment]
Yes I absolutely agree, the option is badly named.  I didn't think of that, the issue really arose when I was using another serverless-plugin (serverless-auto-swagger) that had the option ```disableLogs: true``` and the deploy would fail because I dont't create a log group for those functions. I had the logSubscription enabled globally but I think i'll just take out the global enable, that would solve my issue. Thanks for your time
